### ISSUE TITLE
Outline needs for protein prep for simulation-ready models

### ISSUE THREAD

**Issue by apayne97** [asapdiscovery/asapdiscovery#139]
# Description
There are a bunch of errors recorded on ASAP Notion.

# Related Issues
- #134 
- #47 
- #129 

# ToDo
- [x] make new branch for prepping models for simulation
- [x] #142 

# Questions
- [ ] when should we do these things in our pipeline:
    - [ ] capping
    - [ ] setting protonation states
    - [ ] add solvent
    - [ ] minimization

We can either:
1. make an alternate version of the protein prep script that does all of these things or some subset of these things
2. make an additional step(s) of the pipeline that takes the output of the protein prep script and prepares it for simulation

**Comment by apayne97** [comment]
@JenkeScheen @jchodera @ijpulidos 

For capping, solvating, and setting protonation states, it would be nice to discuss a plan for incorporating them into our current pipeline.

Should we use OpenEye for everything? different options? openfftoolkit?

Should we use a set of protonation states for every system? should we let OpenEye decide?

**Comment by JenkeScheen** [comment]
AFAIK the majority of errors when getting from OE-prepped fragalysis structures to OpenMM are triggered by `openmmforcefields.generators.template_generators`, so perhaps it would be best to move the prepping procedure as close to what OFF recommends as possible. openfftoolkit doesn't a protein prep implementation does it?

I would vote for making [capping, setting protonation states, add solvent, minimization] a separate 'prepping' module as per https://github.com/choderalab/asapdiscovery/issues/134, but having the latter two optional, i.e.:
- capping, setting protonation states by default, enough for docking
- add solvent, minimization optional, if intended for MD

If you think OE can do a good job at setting protonation states (better than it's doing now anyway) I think sticking with OE should be okay. The only thing we'll want to make sure we include though is the enumeration of the catalytic dyad (triad..?) is included as an option. This could of course be implemented in a flexible way, e.g. `system.prepare(add_solvent=True, minimize=True, custom_protonation={"HIS41" : "+", "CYS145" : "-", "HIS163" : 0})`. See [@jchodera's example](https://github.com/choderalab/perses/blob/moonshot-examples/examples/moonshot-sulfonamides/00-prep-receptor.py#L282-L313).

**Comment by apayne97** [comment]
Based on the same example (which is what you're using as well, I think), it looks like we're actually *not* capping! https://github.com/choderalab/perses/blob/moonshot-examples/examples/moonshot-sulfonamides/00-prep-receptor.py#L216
```
 # Both N- and C-termini should be zwitterionic
    # Mpro cleaves its own N- and C-termini
    # See https://www.pnas.org/content/113/46/12997
    opts.GetPrepOptions().GetBuildOptions().SetCapNTermini(False);
    opts.GetPrepOptions().GetBuildOptions().SetCapCTermini(False);
    # Don't allow truncation of termini, since force fields don't have parameters for this
    opts.GetPrepOptions().GetBuildOptions().GetCapBuilderOptions().SetAllowTruncate(False);
    # Delete clashing solvent if needed
    opts.GetPrepOptions().GetBuildOptions().GetCapBuilderOptions().SetDeleteClashingSolvent(True)
    opts.GetPrepOptions().GetBuildOptions().GetSidechainBuilderOptions().SetDeleteClashingSolvent(True)
    # Build loops and sidechains
    opts.GetPrepOptions().GetBuildOptions().SetBuildLoops(True);
    opts.GetPrepOptions().GetBuildOptions().SetBuildSidechains(True);
```

**Comment by apayne97** [comment]
@JenkeScheen what is the minimal set of things that are currently missing in the asapdiscovery prepped structures (ignoring the errors - hopefully we can get rid of all of those) that is making you continue to use John's script instead of ours for prepping the structures?
is there anything besides:
- [ ] setting protonation variants of catalytic dyad 
- [ ] writing out ligand sdf file + protein pdb file separately

Is there a simple perses simulation script we can use to validate an improved prep simulation? Something that could be added here:
- #142 

I need something I can run on a system that isn't working, prep it with the new script, and show that it works.

Maybe @ijpulidos can assist?

**Comment by ijpulidos** [comment]
@apayne97 I guess we also need something that caps the molecules, or is that already handled by your prepping scripts?

**Comment by ijpulidos** [comment]
> I need something I can run on a system that isn't working, prep it with the new script, and show that it works.
> 
Yes, that's a good idea, we would also want to make that a test for the tools/scripts in general.

**Comment by apayne97** [comment]
@ijpulidos i think we actually shouldn't cap, because these are the actual termini of Mpro (i.e. they should in fact be zwitterionic)
See from the comment above:
```
# Both N- and C-termini should be zwitterionic
# Mpro cleaves its own N- and C-termini
# See https://www.pnas.org/content/113/46/12997z
```

**Comment by apayne97** [comment]
@ijpulidos here's another simple question - do you think a perses / simulation test should go in `asapdiscovery.modeling` or `asapdiscovery.simulation`? Because the output of `modeling` is the input for this test but the test will use the environment in the simulation module.

**Comment by ijpulidos** [comment]
@apayne97 I guess it depends on what we are testing exactly, if we are testing the functions/scripts in `asapdiscovery-simulation` then I think they should be there.

**Comment by apayne97** [comment]
We'd like to test whether the modeling functions have done a good enough job so as not to throw errors when trying to run simulations! So it's kind of both?
