### ISSUE TITLE
Implement docking-score based clustering of structural data

### ISSUE THREAD

**Issue by apayne97** [asapdiscovery/asapdiscovery#85]
A core question we'd like to ask is: what is the best way to tell whether we have a diverse enough set of structures to enable accurate pose prediction of compound X? 

One way to do this would be to use information about chemical similarity of structure-enabled complexes to compound X, but here we would like to consider just clustering all N structures by the vector of docking scores to M compounds.

I wonder if there's a way to make this at all a physics-informed approach?

# Todo
- [ ] prepare N vectors of M compounds
- [ ] perform clustering of N structures
- [ ] how different are the clusters in their scores? is there a good correlation with scaffold-based clustering?
